### ISSUE TITLE
Search finds products in hidden category

### ISSUE THREAD

**Issue by KlausAnt** [Vinai/groupscatalog2#126] opened 2015-11-02 22:05 UTC
Thanks for a great extension, first of all :-)
If a product is placed in a category that is set to hide from groups = not logged in, the product can still be searched and viewed on the product list page if you are not logged in.
If product name is clicked the page will default to login page as expected. The product is set to hide from groups = use default = show products by default.

Is this default behavior to be able to view a product, placed in a hidden category?

**Comment by Vinai** [comment] 2015-11-03 19:53
Hi, this is indeed the intended behavior. In Magento, Products and Categories are independent entities.
A product can be assigned to any number of categories.
For that reason products have to be hidden from customer groups, too, just as the categories.

**Closed by Vinai** 2015-11-03 19:53 UTC
